defaults: &defaults
    docker:
        - image: circleci/openjdk:8-jdk
    working_directory: /home/circleci/project

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                    - java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
            - restore_cache:
                keys:
                    - scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
            - run:
                command: ./sbin/buildAll.sh
            - run:
                command: ./sbin/testAll.sh
            - store_test_results:
                path: "testResults"
            - persist_to_workspace:
                root: /home/circleci/project
                paths:
                    - CitibikeApiProducer/build/
                    - RawDataSaver/target/
                    - StationConsumer/target/
                    - StationTransformerNYC/target/
            - run:
                command: ls /home/circleci/project/
            - save_cache:
                key: scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
                paths:
                    - "~/.ivy2/cache"
            - save_cache:
                key: java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
                paths:
                    - "~/.gradle"
#    test:
#        <<: *defaults
#        steps:
#            - checkout
#            - run:
#                  command: ./sbin/testAll.sh
#            - store_test_results:
#                  root: /home/circleci/project
#                  path: "testResults"

    deploy:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                  - "cb:b4:08:ac:12:ba:a6:3d:86:51:1f:d5:bf:37:d2:a2"
            - run:
                command: ./sbin/deploy.sh $BASTION_PUBLIC_IP $TRAINING_COHORT

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: 
                            - master
                            - TWDU-#1
                            - start
#            - test:
#                requires:
#                    - build
            - approve-deploy:
                type: approval
                requires: 
                    - build
#                    - test
            - deploy:
                requires:
                    - approve-deploy

